IBM/ibm-block-csi-driver

- controller/array_action/array_connection_manager.py
- controller/array_action/array_mediator_interface.py
- controller/array_action/array_mediator_svc.py
- controller/array_action/array_mediator_xiv.py
- controller/controller_server/csi_controller_server.py
- controller/tests/array_action/array_connection_manager_test.py
- controller/tests/controller_server/csi_controller_server_test.py
This PR is mainly refactor the array interface to use abstractproperty and also set max_connection=3.
Full detail below:
1. Update max_connections from 3 to 2 (based on architecture review)
2. Add missing interface - disconnect().  It was implemented by xiv mediator but was not exist in the interface.
3. Refactor few consts that were specified in the array specific mediator to be a formal 
abc.abstractproperty of the mediator interface. So every mediator will have to implement it. Here is the list of attributes (old -> new):
- ARRAY_TYPE -> array_type
- CONNECTION_LIMIT -> max_connection
- PORT -> port
- MAX_VOL_NAME_LENGHT -> max_vol_name_length
4. Refactor function minimal_volume_size_in_bytes() to be a property of the interface.
5. Remove MAX_CONNECTION_RETRY const from XIV mediator. …
> CSI-108: Improve array interface + set max_connection to 2

- controller/array_action/array_mediator_interface.py
- controller/array_action/array_mediator_xiv.py
- controller/array_action/utils.py
this PR is fixing an issue regarding properties not being able to be called via Class object (only via instance) 
so a classproperty was added to allow this.
Its a fix for the https://github.com/IBM/ibm-block-csi-driver/pull/16.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/17)
> change property to class property

- .dockerignore
- Dockerfile-csi-node
- Dockerfile-csi-node.test
- Makefile
- go.mod
- go.sum
- scripts/ci/build_push_images.sh
- scripts/ci/jenkins_pipeline_csi
Build csi node as docker image and trigger it as part of the build pipeline in jenkins. So from now on there is ready csi node image in the internal artifactory after every push in git (together with csi controller image which already there).
- Building csi node based on centos7 (maybe we will change to UBI later) and locate the exec inside /root and also copy the config.yaml file.
- Uses multistage build for compilation:
- Uses go.1.12.6 image
- Make sure go mod in dedicated docker cache layer to avoid downloading every time.
- Using `make ibm-block-csi-driver` inside the dockerfile to build the csi node (so dockerfile use the make but also develop can use it locally to compile)
- Remove .git from .dockerignore in order to have the .git inside the docker image build stage to get the …
> Feature/csi node docker build in CI pipeline

- controller/scripts/entrypoint.sh
change controller entrypoint to  use python3.6 in the entrypoint script. (instead of default python2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/31)
> Fix\change python entrypoint to use python3.6

- deploy/kubernetes/v1.13/ibm-block-csi-driver.yaml
- deploy/kubernetes/v1.14/ibm-block-csi-driver.yaml
- node/pkg/driver/node.go
- node/pkg/driver/node_test.go
- scripts/run_yamlcheck.sh
Adding daemonset for csi-node container and its side cars containers(liveness-probe, node-driver-registrar).
The csi-node container (ibm-block-csi-node):
- privileged container
- Pass the spec.nodeName to the csi node (Used for GetNodeInfo)
- The container has the following host path : 
path: /var/lib/kubelet/pods         ## This volume is where the driver mounts volumes
path: /var/lib/kubelet/plugins/ibm-block-csi-driver/   ## This volume is where the socket for kubelet->driver communication is done
path: /var/lib/kubelet/plugins
/var/lib/kubelet/plugins_registry/    ## This volume is where the node-driver-registrar registers the plugin with kubelet
/dev           ## To discover the new devices
/etc/iscsi/   ## To retrieve the IQN for the GetNodeInfo API
/sys            ## To discover …
> csi-node daemonset in to the plugin manifest

- README.md
- deploy/kubernetes/v1.13/ibm-block-csi-driver.yaml
- Moving daemonset and stateful-set resources to use apps/v1 instead of apps/v1beta.
- It also adding selector to the stateful-set which is mandatory for app/v1.
- Updating the README to show daemonset as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/33)
> align to v1 in daemonset and statefulset and also add selector

- Dockerfile-csi-controller
- controller/requirements.txt
@shay-berman  and @olgashtivelman 
In requirements.txt
futures==3.2.0 need to change to futures==3.1.1 to support python3, from the https://pypi.org/project/futures/3.2.0/, we can get that:
It should not be installed on Python 3, although there should be no harm in doing so, as the standard library takes precedence over third party libraries.
and pip also need to upgrade, otherwise, gcc error will be raised
Jira ticket: https://jira.xiv.ibm.com/browse/CSI-287
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/34)
> update dockerfile and requirements to support python3

- Dockerfile-csi-controller.test
HI @ranhrl , like the Dockerfile-csi-controller,  pip3 in Dockerfile-csi-controller.test also need to upgrade to 19.1.1. other wise gcc error will be thrown
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/36)
> upgrade pip3 version for Dockerfile-csi-controller.test

- node/pkg/driver/device_connectivity/errors.go
- node/pkg/driver/node.go
Suggestion for moving the mount operation from the nodestage to the nodepublishvolume.
1. nodestage will do the discovery and also mkfs (and testing mount to nodestage, but after testing it will unmount it). 
2. nodestage creates the nodeinfo file to the stagingTarget directory (which is not mounted!).
3. Nodepublish volume will get the dm device from the nodestage info file (on the stagingPath) and will mount it to the targetPath(the final path of the pod)
4. Nodeunpublishvolume will do the same as before, just unmount the targetPath.
5. nodeunstage will read the stage info file and then delete the dm devices and the sdX devices. (no need to unmount the stagingPath because its never mounted to the staging path with this proposal)
Pros:
1. stageinfo file stored on the node filesystem and …
> Refactor - NodePublishVolume will do the mount instead of NodeStage

- Dockerfile-csi-controller
- Dockerfile-csi-node
Moving to the shiny UBI base images instead of `centos7`, which is one more step to become  Container [Certification](https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/certify-your-application/containers-with-red-hat-universal-base-image-ubi) for Redhat.
[UBI](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/getting_started_with_containers/using_red_hat_universal_base_images_standard_minimal_and_runtimes) is the new Redhat\IBM `thin` base image for containers, many advantages for using UBI, one of them is a small footprint (just 101MB).
So good bye Alpine(and Centos), welcome UBI base image ;-)
New base image is `registry.access.redhat.com/ubi8/ubi-minimal:8.0`.
Why ubi-minimal?  because CSI node doesn't need much …
> Feature/shiny UBI images for CSI plugin

- deploy/kubernetes/v1.13/ibm-block-csi-driver.yaml
- deploy/kubernetes/v1.14/ibm-block-csi-driver.yaml
- node/pkg/driver/node.go
- node/pkg/driver/node_utils_test.go
- scripts/ci/run_node_server_for_csi_test.sh
Ran tested the plugin on FC environemnt without any iscsi service on the worker nodes (which is the common use case in Fc env). And he find an issue that the csi node is failing due to missing /etc/iscsi directory.
So this PR fix 
Before this PR /etc/iscsi hostpath was specified in the yaml. So I removed this specific hostpath from the yaml and fixed the code to take /etc/iscsi from the /host/etc/iscsi which is already the hostpath of the worker node. So there is no really need to specify also /etc/iscsi in the yaml if we already have hostpath / inside csi node in /host directory (reminder - csi node requires the / of the worker node because it discover multipath devices inside the csi node container).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Fix/CSI-485 works without /etc/iscsi directory

- deploy/kubernetes/v1.13/ibm-block-csi-driver.yaml
- deploy/kubernetes/v1.14/ibm-block-csi-driver.yaml
to get the fix https://github.com/kubernetes-csi/external-attacher/pull/168
https://github.com/kubernetes-csi/external-attacher/pull/168#issuecomment-530803871
related to -> https://github.com/IBM/ibm-block-csi-driver/pull/70
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/71)
> Upgrade attacher to 1.2.1 

- scripts/ci/helper_to_push_docker_image.sh
- Helper script that pull an source image [registry1/image:tag] and then push to different registry target[ registry1/image:tag].
- Script also tag latest on the image is requires.
- The script do validation to make sure the image on the target is not exist already, and also validate the target image is downloadable at the end.
- It uses in the CI to publish the CSI driver new images from internal registry to DockerHub:
https://hub.docker.com/r/ibmcom/ibm-block-csi-driver-node
https://hub.docker.com/r/ibmcom/ibm-block-csi-driver-controller
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/73)
> helper script for pushing images to dockerhub

- node/pkg/driver/sync_lock.go
This PR tries to fix issue [CSI-505](https://jira.xiv.ibm.com/browse/CSI-505).
The problem is that we should not print a sync.Map!!
Although sync.Map is goroutine safe, you must use the methods it exposes. If not, it is not safe. So you can not print a whole sync.Map because it doesn't have such a method to return its conent. If you print the sync.Map directly, all the fields will be printed. It has 4 fields: mu, read, dirty and misses. "dirty" is a map, and it is not safe, that's the root cause we faced: during printing "dirty", some items are removed, and we enconter a "index out of range" error.
We can use sync.Map.Range to get all kvs, but I don't think it is necessary.
In addition this PR contains fix with https://github.com/IBM/ibm-block-csi-driver/pull/80 (see detail in PR #80 ) …
> BUG fix - avoid logging the syncMap content + loadorstore (not thread safe)

- README.md
- node/pkg/driver/device_connectivity/errors.go
1. as mentioned in the README file, the customer must set at least 2 connection to the storage system in every node in the cluster.
If only one connection exist, then the CSI driver may fail during descovering the multipath device, because multipathd will not generate  /dev/dm-x  if only 1 connection exist.
So this PR is to clarify the error message, so the customer will see error message that saying you need to connection with at least 2 paths to the storage system.
@ranhrl  thanks for catching this error message.
2. Update README with systemctl enable multipathd
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/87)
> meaningful error messages for dm device not found  + README update to enable multipathd

- controller/array_action/array_mediator_svc.py
- controller/tests/array_action/svc/array_mediator_svc_test.py
Bug fix for CSI-528
The root cause is that our code will converts the iqn to a list regardless of whether it is a list or not
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/86)
> fix CSI-528

- Dockerfile-csi-controller
- Dockerfile-csi-node
- README.md
- common/config.yaml
- controller/tests/controller_server/csi_controller_server_test.py
- deploy/kubernetes/v1.13/ibm-block-csi-driver.yaml
- deploy/kubernetes/v1.14/ibm-block-csi-driver.yaml
- node/pkg/driver/version_test.go
**(A) update to UBI7 base image**
Per Redhat support matrix([HERE](https://access.redhat.com/support/policy/rhel-container-compatibility)), since CSI GA v1 support RHEL7.x worker nodes, then the related UBI image of the CSI container must be ubi7 and not ubi8.
So this PR change the node and controller base image
1. node -> ubi7/ubi-minimal:7.7-138  (instead of ubi8/ubi-minimal:8.0-213)
https://access.redhat.com/containers/#/registry.access.redhat.com/ubi7/ubi-minimal
2. controller -> ubi7/python-36:1-56.1568971386 (instead of ubi8/python-36:1-58)
https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/ubi7/python-36
thanks @27149chen for catching this support matrix page. (CSI-574)
Also added PR for the operator as well -> …
> Improve/ubi7 per Redhat support matrix + Updage version for GA 1.0.0

- deploy/kubernetes/v1.14/ibm-block-csi-driver.yaml
per @xyanyang request.
Note - remember for v1.0 the deployment method is only by the operator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/93)
> fix missing seperator in 1.14 yaml (per Xiao request)

- controller/array_action/array_mediator_action.py
- controller/array_action/errors.py
- controller/array_action/messages.py
- controller/controller_server/csi_controller_server.py
- controller/requirements.txt
fix the performance issue "CSI-536 slow svc map operation" for ControllerPublishVolume/ControllerUnpublishVolume
since we only have 2 storage ssh connections to handle grpc request, so it's easily to encounter the Exception NoConnectionAvailableException.
when external-attacher receives grpc error, it will put this VA(VolumeAttachment) back to vaQueue with exponential backoff retry time(that is delay to put it back to queue).
so the request interval will reach 5 minutes after several times failure(retryIntervalMax is 5*time.Minute)
solution
set a timeout 11s(since csiTimeout for kubelet is 15 second), during this time, retry to map volume if encounter the NoConnectionAvailableException, response to external-attacher after the timeout
---
This change is [<img …
> fix performance issue csi-536 slow svc map operation

- deploy/kubernetes/v1.13/ibm-block-csi-driver.yaml
- deploy/kubernetes/v1.14/ibm-block-csi-driver.yaml
Since @27149chen @wangpww  encounter issues in the openshift certification regarding setting the [hostNetwork](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/) on the node \ controller pod spec.
I tested it without hostNetwor:true (which means its by default false) and it works well (tested it via the original yamls).
I will create similar PR on the https://github.com/IBM/ibm-block-csi-operator as well to fix it in the operator side of thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/94)
> remove pod.spec.hostNetwork:true, its not needed

- node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go
in the func FlushMultipathDevice, we use os.Open to open the multipath disk to check whether the disk exists or not, but we forget to close it after that.
this causes: 
if we run the "multipath -f /dev/dm-x" failed at the first time, we try to run this command again, we will get an error, it says "the disk map in use".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/95)
> add defer to close multipath disk in FlushMultipathDevice

- README.md
- USAGE-DETAILS.md
- deploy/kubernetes/examples/template-array-secret.yaml
Use stringData for storage address and usernames
No code change is needed. Updated only readme.
so instead of 
```
kind: Secret
apiVersion: v1
metadata:
name: <VALUE-1>
namespace: kube-system
type: Opaque
data:
username: <VALUE-2 base64>        # Array username.
password: <VALUE-3 base64>        # Array password.
management_address: <VALUE-4 base64,VALUE-5 base64> # Array managment addresses
```
user can do this:
```
kind: Secret
apiVersion: v1
metadata:
name: <VALUE-1>
namespace: kube-system
type: Opaque
stringData:
management_address: <VALUE-2,VALUE-3> # Array managment addresses
username: <VALUE-4>                   # Array username.  
data:
password: <VALUE-5 base64>            # Array password.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> CSI-481_secret_stringData

- deploy/kubernetes/v1.13/ibm-block-csi-driver.yaml
- deploy/kubernetes/v1.14/ibm-block-csi-driver.yaml
same as https://github.com/IBM/ibm-block-csi-operator/pulls but for the old deployment method - to validate in on CI (since Operator still not run in CI)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/100)
> add hostIPC to avoid multipath -f stuck on csi node

- node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go
fix the node crash issue
when "multipath -f dm-x" is timeout, the os.Stat(fullDevice) will return nil to the err, then call err.Error() will get a panic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/102)
> update FlushMultipathDevice to fix nil pointer dereference issue

- Dockerfile-csi-controller
CSI controller base image change to the latest tag
Old tag  -> registry.access.redhat.com/ubi7/python-36:1-56.1568971386
New tag -> registry.access.redhat.com/ubi7/python-36:1-58
the new tag 1-58 fix patch issue inside the image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/104)
> using new tag 1-58

- Dockerfile-csi-controller
boringssl does not support s390x:
https://github.com/grpc/grpc/issues/13369
so I changed the ssl lib of python grpc to openssl:
https://stackoverflow.com/a/52770127
> change grpc linkage from boringssl to openssl

- Dockerfile-csi-controller
- Dockerfile-csi-controller.test
a continuation of https://github.com/IBM/ibm-block-csi-driver/pull/249
> CSI-2350 finish allowing openssl 1.0.2

- scripts/ci/run_community_csi_test.sh
- scripts/ci/run_controller_server_for_csi_test.sh
- scripts/ci/run_node_server_for_csi_test.sh
remove the driver containers only after the logs were collected from both standard streams
> CSI-2153 make community test node log full

- node/pkg/driver/node.go
- node/pkg/driver/node_test.go
allow mounting xfs uuid that is not unique, for scenarios with pvc from snapshot/clone.
similar to https://github.com/ceph/ceph-csi/pull/1009
> CSI-1793 fix mounting a copy of xfs with same uuid

- Dockerfile-csi-controller
- Dockerfile-csi-controller.test
- Dockerfile-csi-node
even CRYPTOGRAPHY_ALLOW_OPENSSL_102 won't make cryptography compile (the current `cryptography-3.3.1-cp36-abi3-manylinux2010` wheel supports only x86).
so we're actually downgrading our [Red Hat support](https://access.redhat.com/support/policy/rhel-container-compatibility) from Tier 2 to Tier 3 for users with RHEL 7.x worker machines.
> Upgrade to ubi8

- node/pkg/driver/executer/executer.go
- node/pkg/driver/node.go
- node/pkg/driver/node_test.go
- node/pkg/driver/node_utils.go
in [contrast to ext4](https://linux.die.net/man/8/resize2fs), a mount-point directory [should be used](https://linux.die.net/man/8/xfs_growfs) to expand xfs.
and since `NodeExpandVolume` [may be called before NodePublishVolume](https://github.com/container-storage-interface/spec/blob/v1.3.0/spec.md#nodeexpandvolume), it cannot rely on the publish target path to be mounted, so `NodeStageVolume` must mount the staging path in advance.
please note:
1. this means we cannot create the (unnecessary) stage info file in the staging directory anymore
2. this should not affect raw block
> CSI-2471 fix arg for xfs_growfs

- Dockerfile-csi-controller
- Dockerfile-csi-controller.test
See some issue mentioned on the cryptography repo - https://github.com/pyca/cryptography/issues/5771
> Fix power arch build due to rust cryptography compilation failure

- Dockerfile-csi-controller
- Dockerfile-csi-node
- common/config.yaml
- node/pkg/driver/version_test.go
It's based on [this ](https://github.com/IBM/ibm-block-csi-driver/commit/eb4fe0d6afb46a26d74835c458302c839e9e6312)commit.
> CSI-2842 bump driver version to 1.6.0

- controller/scripts/unitests.sh
remove:
```
+ unset BASH_ENV PROMPT_COMMAND ENV
+ grep -q '^CentOS Linux release 7'
+ head /etc/redhat-release
+ grep -q '^Red Hat Enterprise Linux\( Server\)\? release 7'
+ head /etc/redhat-release
+ source /opt/app-root/bin/activate
++ deactivate nondestructive
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
++ '[' -n '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/opt/app-root
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/opt/app-root/src/.local/bin/:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/opt/app-root/bin:/opt/app-root/src/.local/bin/:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ export …
```
> avoid scl_enable print noise in CI

- Dockerfile-csi-controller
missed in https://github.com/IBM/ibm-block-csi-driver/pull/271
> disallow old openssl

- scripts/ci/Jenkinsfile
**Issue details**
Faced with `docker login` issue on power slave builder:
`docker login -u  ******** -p ******** https://stg-artifactory.haifa.ibm.com:5030`
`Error: credentials key has https[s]:// prefix`
One direction was to remove the `https` from registry URL but this is not supported by the Jenkins docker plugin:
`java.net.MalformedURLException: unknown protocol: stg-artifactory.haifa.ibm.com `
> CSI-3595: Remove https from artifactory url for docker login

- controller/tests/array_action/test_storage_agent.py
the non-reviewed https://github.com/IBM/ibm-block-csi-driver/pull/170 has many issues, this fixes one of them:
a `sleep` does not guarantee that the desired state is always reached (in this case, that all remaining threads have created, and are still using, their mediator in the pool), no matter what hardcoded waiting time is chosen
> CSI-2142 fix unstable mediator pool unit test

- node/logger/logger.go
a fix for https://github.com/IBM/ibm-block-csi-driver/pull/485
before:
```
2022-03-30 09:25:55,3309 DEBUG	[265] [-] (logger.go:245) - >>>> NodeGetCapabilities
```
after:
```
2022-04-03 14:07:59,432 DEBUG	[26] [-] (node.go:778) - >>>> NodeGetCapabilities
```
> fix log wrapper caller

- scripts/ci/run_csi_test_client.sh
adding the no-cache flag to docker build command when build the image for the community tests to make sure we pull the latest  version of community tests repository each time.
> CSI-4072_adding_no_cache_flag

- node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go
it [seems](https://github.com/hreinecke/sg3_utils/blob/v1.46/src/sg_inq.c#L140) the internal timeout of the command is 60 seconds, IMO we can wait at least 10 seconds, in case there are network delays
> CSI-4369 fix sg_inq timeout

- Dockerfile-csi-test
Due to failing community tests - Needed to update go in the container to 1.18 in order to align with community code in go.mod
> Community tests - update go in container to 1.18
